#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dynamicArray' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def dynamicArray(n, queries):
    # Write your code here
    last_ans = 0
    empty_list = [[]] * n
    result = []
    for query in queries:
        index = (query[1] ^ last_ans) % n
        if query[0] == 1:
            empty_list[index] = empty_list[index] + [query[2]]
        else:
            number = query[2] % len(empty_list[index])
            last_ans = empty_list[index][number]
            result.append(last_ans)

    return result
    print(result)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    q = int(first_multiple_input[1])

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    result = dynamicArray(n, queries)
    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
